[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://ruby.social/.well-known/webfinger?resource=acct:@scottw@ruby.social"
  status = 200